### ISSUE TITLE
twitter video issue

### ISSUE THREAD

**Issue by ahsanfkr** [tenebo/Hitomi-Downloader-Mac#14]
Has anyone else here experienced issues with downloading Twitter media, especially videos comes without audio? If others are facing the same problem, i hope someone please fix it

**Comment by tenebo** [comment]
Have you ever attached the cookie data before downloading? Please show your task info.

**Comment by ahsanfkr** [comment]
here it is what i found at task info which comes without audio, i use M1 btw, hope u can figure it out and fix it, thanks!

```
call... UserMedia
-show_streams -print_format json -v error "[23-12-13] 1734920171855483093_p0.mp4"
-show_streams -print_format json -v error "[23-12-13] 1734920171855483093_p0.mp4"
Traceback (most recent call last):
 File "image_reader", line 32, in QPixmap
 File "image_reader", line 151, in QPixmap_
 File "PIL/Image", line 3298, in open
PIL.UnidentifiedImageError: cannot identify image file '/Users/xxxxx/Documents/hitomi_downloaded_twitter/example \U0001faad (@example)/[23-12-13] 1734920171855483093_p0.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "image_reader", line 50, in QPixmap
 File "ffmpeg", line 757, in capture_fast
 File "decorator", line 232, in fun
 File "constants", line 913, in try_
 File "constants", line 882, in try_
 File "ffmpeg", line 772, in capture
 File "ffmpeg", line 827, in get_info
 File "ffmpeg", line 821, in get_info
 File "ffmpeg", line 133, in run
 File "patch_subprocess", line 16, in __init__
 File "subprocess", line 971, in __init__
 File "subprocess", line 1863, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/System'

stop
EOT: https://twitter.com/maujdmalaikatmu  (13.6s)
```
