### ISSUE TITLE
Please read this before posting an issue

### ISSUE THREAD

**Issue by tenebo** [tenebo/Hitomi-Downloader-Mac#15]
If it does not work, please provide more details on how it is not working, otherwise, I can't help you. The easiest way is to show task information. You can check it by `Control-click`- `Info... (I)`

**Comment by pkpkthis** [comment]
Thank you for making the Mac version

When I download the newly added https://chzzk.naver.com/ , I don't think I can download videos for those over 19 years old. Is there a solution? The error appears as Invalid: [etc] https://chzzk.naver.com/video/261260 . The video I'm trying to download is https://chzzk.naver.com/video/261260 . Other than this, all other videos over 19 years old can't be downloaded. Below is the work information.

Invalid: [etc] https://chzzk.naver.com/video/261260

version: 4.0-1.0 (24-02-10 19:36:39 UTC)
platform / locale: macOS-14.2.1-arm64-arm-64bit / ko_kr
order / group / uid: 2 / False / ecd5cb74031d41c8858d2f96754c77a7
input: https://chzzk.naver.com/video/261260
type: etc
single: True
url: https://chzzk.naver.com/video/261260
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1709146179.824181 (24-02-28 18:49:39 UTC) - 361s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2024.02.25.232703
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
extractor: chzzk
get_video: True, https://chzzk.naver.com/video/261260
[debug] [chzzk:video] Extracting URL: https://chzzk.naver.com/video/261260
[debug] [chzzk:video] 261260: Downloading video info
[debug] [chzzk:video] 261260: Downloading video playback
get_video: True, https://chzzk.naver.com/video/261260
[debug] [chzzk:video] Extracting URL: https://chzzk.naver.com/video/261260
[debug] [chzzk:video] 261260: Downloading video info
[debug] [chzzk:video] 261260: Downloading video playback
get_video: True, https://chzzk.naver.com/video/261260
[debug] [chzzk:video] Extracting URL: https://chzzk.naver.com/video/261260
[debug] [chzzk:video] 261260: Downloading video info
[debug] [chzzk:video] 261260: Downloading video playback
get_video: True, https://chzzk.naver.com/video/261260
[debug] [chzzk:video] Extracting URL: https://chzzk.naver.com/video/261260
[debug] [chzzk:video] 261260: Downloading video info
[debug] [chzzk:video] 261260: Downloading video playback
ERROR: [chzzk:video] 261260: Unable to download video playback: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
get_video: False, https://chzzk.naver.com/video/261260
[debug] [chzzk:video] Extracting URL: https://chzzk.naver.com/video/261260
[debug] [chzzk:video] 261260: Downloading video info
[debug] [chzzk:video] 261260: Downloading video playback
get_video: False, https://chzzk.naver.com/video/261260
[debug] [chzzk:video] Extracting URL: https://chzzk.naver.com/video/261260
[debug] [chzzk:video] 261260: Downloading video info
[debug] [chzzk:video] 261260: Downloading video playback
get_video: False, https://chzzk.naver.com/video/261260
[debug] [chzzk:video] Extracting URL: https://chzzk.naver.com/video/261260
[debug] [chzzk:video] 261260: Downloading video info
[debug] [chzzk:video] 261260: Downloading video playback
get_video: False, https://chzzk.naver.com/video/261260
[debug] [chzzk:video] Extracting URL: https://chzzk.naver.com/video/261260
[debug] [chzzk:video] 261260: Downloading video info
[debug] [chzzk:video] 261260: Downloading video playback
ERROR: [chzzk:video] 261260: Unable to download video playback: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
stop
Traceback (most recent call last):
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/extractor/common", line 864, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 457, in urlopen
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/YoutubeDL", line 4097, in urlopen
   return self._request_director.send(req)
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/networking/common", line 115, in send
   response = handler.send(request)
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/networking/_helper", line 204, in wrapper
   return func(self, *args, **kwargs)
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/networking/common", line 326, in send
   return self._send(request)
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/networking/_requests", line 351, in _send
   raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/YoutubeDL", line 1593, in wrapper
   return func(self, *args, **kwargs)
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/YoutubeDL", line 1728, in __extract_info
   ie_result = ie.extract(url)
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/extractor/common", line 732, in extract
   ie_result = self._real_extract(url)
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/extractor/chzzk", line 116, in _real_extract
   formats, subtitles = self._extract_mpd_formats_and_subtitles(
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/extractor/common", line 2548, in _extract_mpd_formats_and_subtitles
   periods = self._extract_mpd_periods(*args, **kwargs)
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/extractor/common", line 2558, in _extract_mpd_periods
   res = self._download_xml_handle(
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/extractor/common", line 1050, in download_handle
   res = self._download_webpage_handle(
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/extractor/common", line 920, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/extractor/common", line 877, in _request_webpage
   raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [chzzk:video] 261260: Unable to download video playback: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor/etc_downloader", line 67, in get_video
 File "decorator", line 232, in fun
 File "constants", line 918, in try_
 File "constants", line 887, in try_
 File "extractor/etc_downloader", line 99, in _get_video
 File "extractor/etc_downloader", line 95, in _get_video
 File "ytdl", line 465, in extract_info
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/YoutubeDL", line 1582, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/YoutubeDL", line 1611, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 408, in report_error
yt_dlp.utils.DownloadError: ERROR: [chzzk:video] 261260: Unable to download video playback: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1373, in start
 File "utils", line 1452, in start_
 File "extractor/etc_downloader", line 31, in read
 File "extractor/etc_downloader", line 79, in get_video
 File "decorator", line 232, in fun
 File "constants", line 918, in try_
 File "constants", line 887, in try_
 File "extractor/etc_downloader", line 99, in _get_video
 File "extractor/etc_downloader", line 95, in _get_video
 File "ytdl", line 465, in extract_info
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/YoutubeDL", line 1582, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ytdl/yt_dlp/yt_dlp/YoutubeDL", line 1611, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 408, in report_error
yt_dlp.utils.DownloadError: ERROR: [chzzk:video] 261260: Unable to download video playback: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

Invalid: fail=True
EOT: https://chzzk.naver.com/video/261260  (1.2s)
