### ISSUE TITLE
youtube download issues

### ISSUE THREAD

**Issue by zettai1011** [tenebo/Hitomi-Downloader-Mac#25]
At the bottom, it says CPU error

Twitch content is downloadable YouTube won't work

Neuro-Sama V3 x cerberVT sings MOGU MOGU YUMMY! [Duet] by Nekomata Okayu [karaoke Cover Version]

version: 4.0-1.0 (24-02-10 19:36:39 UTC)
platform / locale: macOS-14.5-arm64-arm-64bit / ko_kr
order / group / uid: 0 / False / e3897f2769be4eb383c4e921a2770c16
input: https://www.youtube.com/watch?v=nkggUGLu8Qk
type: youtube
single: True
url: https://www.youtube.com/watch?v=nkggUGLu8Qk
dir: /Users/hojun/Documents/hitomi_downloaded_youtube
zip: 
artist: NeuroClips
valid / done: False / True
range / range_p: None / None
time: 1719449021.016669 (24-06-27 00:43:41 UTC) - 146s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: {'format': 'mp4', 'res': 4320, 'abr': 192}
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True, 'mode': 'query'}
admin: False
goodbyedpi: None
ytdl: yt_dlp 2024.06.24.232830
pinned: False
extras: {}
live: False
changed: True

[File Names]
[0001] /Users/hojun/Documents/hitomi_downloaded_youtube/Neuro-Sama V3 x cerberVT sings MOGU MOGU YUMMY! [Duet] by Nekomata Okayu [karaoke Cover Version] (nkggUGLu8Qk).mp4

[URLs]
[0001] Video(https://www.youtube.com/watch?v=nkggUGLu8Qk)    --->    https://rr8---sn-ixaav8pnpvo-pjos.googlevideo.com/videoplayback?expire=1719470622&ei=vrV8Zs3VJZOV0-kP8pWfwA0&ip=42.82.58.168&id=o-AHQcBOM6jXohn7dvDTnzN3Gw0ml6o9IzEZdmVhChFZuu&itag=299&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=J9&mm=31%2C29&mn=sn-ixaav8pnpvo-pjos%2Csn-3pm7kne7&ms=au%2Crdu&mv=m&mvi=8&pl=21&initcwndbps=866250&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=161581758&dur=237.199&lmt=1713644788177562&mt=1719448623&fvip=4&keepalive=yes&c=IOS&txp=6309224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAMldWtMMmCQPRYfaSuZgqZ7SCqvPrPMSQOgMUYBpJsviAiEAtkr7uRu1dnHH7ltNohrhsC6SKJl6wMn8XkWgcsPaEIc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIgaROmKhGKDKM3cgL03nodybyPRhn2qGaya72r4uvr1d4CIQDHwaytmYxQiVyNdnVKUfTtD-0QvOTqCCnm3kCsNrkbGQ%3D%3D

[Messages]
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=nkggUGLu8Qk
[debug] [youtube] nkggUGLu8Qk: Downloading webpage
[debug] [youtube] nkggUGLu8Qk: Downloading ios player API JSON
[debug] [youtube] nkggUGLu8Qk: Downloading player a95aa57a
[debug] [youtube] nkggUGLu8Qk: Downloading m3u8 information
live: not_live
[27p][0.4219409282700422fps][None][None] mhtml [None / None] ─ sb3 - 48x27 (storyboard)
[45p][0.5063291139240507fps][None][None] mhtml [None / None] ─ sb2 - 80x45 (storyboard)
[90p][0.5063291139240507fps][None][None] mhtml [None / None] ─ sb1 - 160x90 (storyboard)
[180p][0.5063291139240507fps][None][None] mhtml [None / None] ─ sb0 - 320x180 (storyboard)
[None][0fps][48.808kbps][48.808] m4a [None / mp4a.40.5] ─ 139 - audio only (low)
[None][0fps][47.972kbps][47.972] webm [None / opus] ─ 249 - audio only (low)
[None][0fps][62.503kbps][62.503] webm [None / opus] ─ 250 - audio only (low)
[None][0fps][129.497kbps][129.497] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)
[None][0fps][120.51kbps][120.51] webm [None / opus] ─ 251 - audio only (medium)
[144p][30fps][None][111.677] mp4 [avc1.4D400C / None] ─ 160 - 256x144 (144p)
[144p][30fps][None][105.972] webm [vp9 / None] ─ 278 - 256x144 (144p)
[240p][30fps][None][249.207] mp4 [avc1.4D4015 / None] ─ 133 - 426x240 (240p)
[240p][30fps][None][208.55] webm [vp9 / None] ─ 242 - 426x240 (240p)
[360p][30fps][None][565.68] mp4 [avc1.4D401E / None] ─ 134 - 640x360 (360p)
[360p][30fps][96.0kbps(fixed)][661.227] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)
[360p][30fps][None][333.245] webm [vp9 / None] ─ 243 - 640x360 (360p)
[480p][30fps][None][1099.308] mp4 [avc1.4D401F / None] ─ 135 - 854x480 (480p)
[480p][30fps][None][605.081] webm [vp9 / None] ─ 244 - 854x480 (480p)
[720p][30fps][None][2105.884] mp4 [avc1.64001f / None] ─ 136 - 1280x720 (720p)
[720p][30fps][None][1031.589] webm [vp9 / None] ─ 247 - 1280x720 (720p)
[720p][60fps][None][3162.036] mp4 [avc1.640020 / None] ─ 298 - 1280x720 (720p60)
[720p][60fps][None][2488.963] webm [vp9 / None] ─ 302 - 1280x720 (720p60)
[1080p][60fps][None][5449.66] mp4 [avc1.64002A / None] ─ 299 - 1920x1080 (1080p60)
[1080p][60fps][None][3971.122] webm [vp9 / None] ─ 303 - 1920x1080 (1080p60)

utime: 1713571200.0

# stream_final
[1080p][60fps][None][5449.66] mp4 [avc1.64002A / None] ─ 299 - 1920x1080 (1080p60)

[None][0fps][48.808kbps][48.808] m4a [None / mp4a.40.5] ─ 139 - audio only (low)
[None][0fps][47.972kbps][47.972] webm [None / opus] ─ 249 - audio only (low)
[None][0fps][62.503kbps][62.503] webm [None / opus] ─ 250 - audio only (low)
[None][0fps][129.497kbps][129.497] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)
[None][0fps][120.51kbps][120.51] webm [None / opus] ─ 251 - audio only (medium)
[360p][30fps][96.0kbps(fixed)][661.227] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)

[None][0fps][48.808kbps][48.808] m4a [None / mp4a.40.5] ─ 139 - audio only (low)
[None][0fps][129.497kbps][129.497] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)
[360p][30fps][96.0kbps(fixed)][661.227] mp4 [avc1.42001E / mp4a.40.2] ─ 18 - 640x360 (360p)

[None][0fps][48.808kbps][48.808] m4a [None / mp4a.40.5] ─ 139 - audio only (low)
[None][0fps][129.497kbps][129.497] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)

[None][0fps][129.497kbps][129.497] m4a [None / mp4a.40.2] ─ 140 - audio only (medium)

filename: Neuro-Sama V3 x cerberVT sings MOGU MOGU YUMMY! [Duet] by Nekomata Okayu [karaoke Cover Version] (nkggUGLu8Qk).mp4
Resolution: 1080p
Codec: avc1.64002A / None
Abr: None
Subtype: mp4
FPS: 60

Download audio: https://rr8---sn-ixaav8pnpvo-pjos.googlevideo.com/videoplayback?expire=1719470622&ei=vrV8Zs3VJZOV0-kP8pWfwA0&ip=42.82.58.168&id=o-AHQcBOM6jXohn7dvDTnzN3Gw0ml6o9IzEZdmVhChFZuu&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=J9&mm=31%2C29&mn=sn-ixaav8pnpvo-pjos%2Csn-3pm7kne7&ms=au%2Crdu&mv=m&mvi=8&pl=21&initcwndbps=866250&vprv=1&svpuc=1&mime=audio%2Fmp4&rqh=1&gir=yes&clen=3840594&dur=237.261&lmt=1713644771644608&mt=1719448623&fvip=4&keepalive=yes&c=IOS&txp=6308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgSj9LjREwZvFfWVzNYZ3u3MVcujLA9WHmw2qnsISOEDkCIQCkK-AazjpRm8iUrhi8tK2sZ-vj16H1RCYOsGxaL08D6g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIgaROmKhGKDKM3cgL03nodybyPRhn2qGaya72r4uvr1d4CIQDHwaytmYxQiVyNdnVKUfTtD-0QvOTqCCnm3kCsNrkbGQ%3D%3D
thumb: https://i.ytimg.com/vi/nkggUGLu8Qk/maxresdefault.jpg
audio done
Convert: /Users/hojun/Documents/hitomi_downloaded_youtube/Neuro-Sama V3 x cerberVT sings MOGU MOGU YUMMY! [Duet] by Nekomata Okayu [karaoke Cover Version] (nkggUGLu8Qk).mp4
rename (1): /private/var/folders/cg/bddl4bs95wz02z1pmcsy79680000gn/T/1db2c7d533de4518a3a6e50fefc58269_a.tmp -> /Users/hojun/Documents/hitomi_downloaded_youtube/tmp6154587c110f4e5fb19e3ac74fa36c66_a.weba
rename (1): /Users/hojun/Documents/hitomi_downloaded_youtube/Neuro-Sama V3 x cerberVT sings MOGU MOGU YUMMY! [Duet] by Nekomata Okayu [karaoke Cover Version] (nkggUGLu8Qk).mp4 -> /Users/hojun/Documents/hitomi_downloaded_youtube/tmp6154587c110f4e5fb19e3ac74fa36c66_v.mp4
-i tmp6154587c110f4e5fb19e3ac74fa36c66_v.mp4 -i tmp6154587c110f4e5fb19e3ac74fa36c66_a.weba -c:v copy -c:a copy -strict experimental -preset ultrafast -threads 0 tmp6154587c110f4e5fb19e3ac74fa36c66_o.mp4
Lazyurl pp Error: /Users/hojun/Documents/hitomi_downloaded_youtube/Neuro-Sama V3 x cerberVT sings MOGU MOGU YUMMY! [Duet] by Nekomata Okayu [karaoke Cover Version] (nkggUGLu8Qk).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 429, in run
 File "hitomi_downloader", line 422, in pp_
 File "extractor/youtube_downloader", line 316, in pp
 File "ffmpeg", line 268, in merge
 File "ffmpeg", line 145, in run
 File "patch_subprocess", line 16, in __init__
 File "subprocess", line 971, in __init__
 File "subprocess", line 1863, in _execute_child
OSError: [Errno 86] Bad CPU type in executable: '/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ffmpeg/ffmpeg'

utime Error: /Users/hojun/Documents/hitomi_downloaded_youtube/Neuro-Sama V3 x cerberVT sings MOGU MOGU YUMMY! [Duet] by Nekomata Okayu [karaoke Cover Version] (nkggUGLu8Qk).mp4
Traceback (most recent call last):
 File "hitomi_downloader", line 443, in run
FileNotFoundError: [Errno 2] No such file or directory

stop
-show_streams -print_format json -v error "Neuro-Sama V3 x cerberVT sings MOGU MOGU YUMMY! [Duet] by Nekomata Okayu [karaoke Cover Version] (nkggUGLu8Qk).mp4"
Traceback (most recent call last):
 File "utils", line 1957, in finish
 File "ffmpeg", line 839, in get_info
 File "ffmpeg", line 833, in get_info
 File "ffmpeg", line 145, in run
 File "patch_subprocess", line 16, in __init__
 File "subprocess", line 971, in __init__
 File "subprocess", line 1863, in _execute_child
OSError: [Errno 86] Bad CPU type in executable: '/Applications/hitomi_downloader_GUI.app/Contents/Frameworks/ffmpeg/ffprobe'

EOT: https://www.youtube.com/watch?v=nkggUGLu8Qk  (21.6s)

**Comment by tenebo** [comment]
I was not able to replicate the error, but please try the newest version and let me know.
