### ISSUE TITLE
Newtoki download issue. 

### ISSUE THREAD

**Issue by libreidy** [tenebo/Hitomi-Downloader-Mac#26]
I get this for newtoki and manatoki. 

Invalid: [manatoki] https://newtoki343.com/webtoon/24018306/배우로서-살겠다

version: 4.0-1.0 (24-02-10 19:36:39 UTC)
platform / locale: macOS-14.5-arm64-arm-64bit / en_us
order / group / uid: 18 / False / ade608ccfc7748349bb131b9ce4c757f
input: https://newtoki343.com/webtoon/24018306/배우로서-살겠다
type: manatoki
single: False
url: https://newtoki343.com/webtoon/24018306/배우로서-살겠다
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1719970771.406162 (24-07-03 01:39:31 UTC) - 923720s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2024.07.12.232729
pinned: False
extras: {}
live: False
changed: False

[File Names]

[URLs]

[Messages]
no title
stop
Traceback (most recent call last):
 File "utils", line 1358, in start
 File "decorator", line 232, in fun
 File "constants", line 918, in try_
 File "constants", line 887, in try_
 File "extractor/manatoki_downloader", line 88, in init
 File "utils", line 661, in __get__
 File "extractor/manatoki_downloader", line 105, in name
 File "extractor/manatoki_downloader", line 122, in get_artist
 File "utils", line 2672, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://newtoki342.com/webtoon/24018306/배우로서-살겠다  (13.5s)

no title
stop
Traceback (most recent call last):
 File "utils", line 1358, in start
 File "decorator", line 232, in fun
 File "constants", line 918, in try_
 File "constants", line 887, in try_
 File "extractor/manatoki_downloader", line 88, in init
 File "utils", line 661, in __get__
 File "extractor/manatoki_downloader", line 105, in name
 File "extractor/manatoki_downloader", line 122, in get_artist
 File "utils", line 2672, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://newtoki343.com/webtoon/24018306/배우로서-살겠다  (8.0s)

no title
stop
Traceback (most recent call last):
 File "utils", line 1358, in start
 File "decorator", line 232, in fun
 File "constants", line 918, in try_
 File "constants", line 887, in try_
 File "extractor/manatoki_downloader", line 88, in init
 File "utils", line 661, in __get__
 File "extractor/manatoki_downloader", line 105, in name
 File "extractor/manatoki_downloader", line 122, in get_artist
 File "utils", line 2672, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://newtoki343.com/webtoon/24018306/배우로서-살겠다  (69.5s)

**Comment by tenebo** [comment]
Please try the newest version
