### ISSUE TITLE
Can't download from manatoki.

### ISSUE THREAD

**Issue by libreidy** [tenebo/Hitomi-Downloader-Mac#27]
I have updated to the 4.1 version. 

Invalid: [manatoki] https://manatoki343.net/comic/19895922

version: 4.0-1.0 (24-06-06 02:50:23 UTC)
platform / locale: macOS-14.5-arm64-arm-64bit / en_us
order / group / uid: 0 / False / d3d2d87213e14e3b930de50f0db454bd
input: https://manatoki343.net/comic/19895922
type: manatoki
single: False
url: https://manatoki343.net/comic/19895922
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1721344137.04795 (24-07-18 23:08:57 UTC) - 214s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: None None
pinned: False
extras: {}
live: False
changed: False

[File Names]

[URLs]

[Messages]
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
no title
stop
Traceback (most recent call last):
 File "utils", line 1377, in start
 File "decorator", line 232, in fun
 File "constants", line 961, in try_
 File "constants", line 930, in try_
 File "extractor/manatoki_downloader", line 86, in init
 File "utils", line 666, in __get__
 File "extractor/manatoki_downloader", line 103, in name
 File "extractor/manatoki_downloader", line 120, in get_artist
 File "utils", line 2728, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://manatoki343.net/comic/19895922  (67.2s)

not f
not f
not f
not f
not f
no title
stop
Traceback (most recent call last):
 File "utils", line 1377, in start
 File "decorator", line 232, in fun
 File "constants", line 961, in try_
 File "constants", line 930, in try_
 File "extractor/manatoki_downloader", line 86, in init
 File "utils", line 666, in __get__
 File "extractor/manatoki_downloader", line 103, in name
 File "extractor/manatoki_downloader", line 120, in get_artist
 File "utils", line 2728, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://manatoki343.net/comic/19895922  (15.7s)

not f
not f
not f
not f
not f
not f
no title
stop
Traceback (most recent call last):
 File "utils", line 1377, in start
 File "decorator", line 232, in fun
 File "constants", line 961, in try_
 File "constants", line 930, in try_
 File "extractor/manatoki_downloader", line 86, in init
 File "utils", line 666, in __get__
 File "extractor/manatoki_downloader", line 103, in name
 File "extractor/manatoki_downloader", line 120, in get_artist
 File "utils", line 2728, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://manatoki343.net/comic/19895922  (16.8s)

**Comment by tenebo** [comment]
Based on the logs, it seems like no updates were made. Can I uninstall and reinstall?

**Comment by libreidy** [comment]
I have reinstalled it multiple times. 

<img width="250" alt="Screenshot 2024-07-19 at 4 06 20 PM" src="https://github.com/user-attachments/assets/37ca0eb3-cc3e-4828-9745-f36f31eb69a3">

Can you double check the uploaded file? The versions doesn't match on the 'about' page. 

Thank you,

**Comment by tenebo** [comment]
I have updated it to the newest version. Could you please try again? The version on the task info should be v4.1-0.0

**Comment by libreidy** [comment]
Hmm..

Still get this..

Invalid: [manatoki] https://newtoki345.com/webtoon/9416732/입학용병

version: 4.1-0.0 (24-06-06 02:50:23 UTC)
platform / locale: macOS-14.5-arm64-arm-64bit / en_us
order / group / uid: 0 / False / 0b31c185811e4954894f9418d0867db9
input: https://newtoki345.com/webtoon/9416732/입학용병
type: manatoki
single: False
url: https://newtoki345.com/webtoon/9416732/입학용병
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1721424764.7993221 (24-07-19 21:32:44 UTC) - 19s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: None None
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
not f
not f
not f
not f
no title
stop
Traceback (most recent call last):
 File "utils", line 1377, in start
 File "decorator", line 232, in fun
 File "constants", line 961, in try_
 File "constants", line 930, in try_
 File "extractor/manatoki_downloader", line 86, in init
 File "utils", line 666, in __get__
 File "extractor/manatoki_downloader", line 103, in name
 File "extractor/manatoki_downloader", line 120, in get_artist
 File "utils", line 2728, in find
utils.SoupNotFound: no title

Invalid: fail=True
EOT: https://newtoki345.com/webtoon/9416732/입학용병  (15.7s)

**Comment by tenebo** [comment]
Please try this https://github.com/tenebo/Hitomi-Downloader-Mac/releases/tag/v4.1-0.1

**Comment by libreidy** [comment]
It worked! Thank you very much.

감사합니다!
